// app/layout.tsx
import type { Metadata } from "next";
import { Figtree, Geist_Mono } from "next/font/google"; // ⬅️ add Figtree
import "./globals.css";
import Providers from "./providers";

const figtree = Figtree({
  weight: ["300","400","500","600","700","800"], // include 700 so font-bold works
  subsets: ["latin"],
  variable: "--font-figtree-var",                // CSS var we’ll map in @theme
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${figtree.variable} ${geistMono.variable}`}>
      {/* apply the family via Tailwind utility */}
      <body className="font-figtree antialiased">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
